/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainSplatRouteImport } from './routes/_main.$'
import { Route as MainAparecerEnGoogleMapsRouteImport } from './routes/_main.aparecer-en-google-maps'
import { Route as MainComoFuncionaRouteImport } from './routes/_main.como-funciona'
import { Route as MainComoSalirPrimeroEnGoogleRouteImport } from './routes/_main.como-salir-primero-en-google'
import { Route as MainComoVeGoogleMiWebRouteImport } from './routes/_main.como-ve-google-mi-web'
import { Route as MainContactoRouteImport } from './routes/_main.contacto'
import { Route as MainFichaGoogleMiNegocioRouteImport } from './routes/_main.ficha-google-mi-negocio'
import { Route as MainPosicionamientoLocalRouteImport } from './routes/_main.posicionamiento-local'
import { Route as MainSeoLocalBarcelonaRouteImport } from './routes/_main.seo-local-barcelona'
import { Route as MainSeoLocalBilbaoRouteImport } from './routes/_main.seo-local-bilbao'
import { Route as MainSeoLocalCordobaRouteImport } from './routes/_main.seo-local-cordoba'
import { Route as MainSeoLocalMadridRouteImport } from './routes/_main.seo-local-madrid'
import { Route as MainSeoLocalMalagaRouteImport } from './routes/_main.seo-local-malaga'
import { Route as MainSeoLocalMurciaRouteImport } from './routes/_main.seo-local-murcia'
import { Route as MainSeoLocalSevillaRouteImport } from './routes/_main.seo-local-sevilla'
import { Route as MainSeoLocalValenciaRouteImport } from './routes/_main.seo-local-valencia'
import { Route as MainSeoLocalZaragozaRouteImport } from './routes/_main.seo-local-zaragoza'
import { Route as MainSeoParaAbogadosRouteImport } from './routes/_main.seo-para-abogados'
import { Route as MainSeoParaAutonomosRouteImport } from './routes/_main.seo-para-autonomos'
import { Route as MainSeoParaClinicasRouteImport } from './routes/_main.seo-para-clinicas'
import { Route as MainSeoParaDentistasRouteImport } from './routes/_main.seo-para-dentistas'
import { Route as MainSeoParaEntrenadoresRouteImport } from './routes/_main.seo-para-entrenadores'
import { Route as MainSeoParaFisioterapeutasRouteImport } from './routes/_main.seo-para-fisioterapeutas'
import { Route as MainSeoParaFontanerosRouteImport } from './routes/_main.seo-para-fontaneros'
import { Route as MainSeoParaGimnasiosRouteImport } from './routes/_main.seo-para-gimnasios'
import { Route as MainSeoParaInmobiliariasRouteImport } from './routes/_main.seo-para-inmobiliarias'
import { Route as MainSeoParaNegociosLocalesRouteImport } from './routes/_main.seo-para-negocios-locales'
import { Route as MainSeoParaPintoresRouteImport } from './routes/_main.seo-para-pintores'
import { Route as MainSeoParaPsicologosRouteImport } from './routes/_main.seo-para-psicologos'
import { Route as MainSeoParaReformasRouteImport } from './routes/_main.seo-para-reformas'
import { Route as MainSeoParaYogaRouteImport } from './routes/_main.seo-para-yoga'
import { Route as MainServiciosRouteImport } from './routes/_main.servicios'
import { Route as MainBlogIndexRouteImport } from './routes/_main.blog.index'
import { Route as MainBlogSlugRouteImport } from './routes/_main.blog.$slug'
import { Route as MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRouteImport } from './routes/_main.blog.seo-local-mejor-estrategia-marketing-nuevo-negocio'
import { Route as ApiPublicSubmitIndexnowRouteImport } from './routes/api/public/submit-indexnow'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSplatRoute = MainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainRoute,
} as any)
const MainAparecerEnGoogleMapsRoute =
  MainAparecerEnGoogleMapsRouteImport.update({
    id: '/aparecer-en-google-maps',
    path: '/aparecer-en-google-maps',
    getParentRoute: () => MainRoute,
  } as any)
const MainComoFuncionaRoute = MainComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => MainRoute,
} as any)
const MainComoSalirPrimeroEnGoogleRoute =
  MainComoSalirPrimeroEnGoogleRouteImport.update({
    id: '/como-salir-primero-en-google',
    path: '/como-salir-primero-en-google',
    getParentRoute: () => MainRoute,
  } as any)
const MainComoVeGoogleMiWebRoute = MainComoVeGoogleMiWebRouteImport.update({
  id: '/como-ve-google-mi-web',
  path: '/como-ve-google-mi-web',
  getParentRoute: () => MainRoute,
} as any)
const MainContactoRoute = MainContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => MainRoute,
} as any)
const MainFichaGoogleMiNegocioRoute =
  MainFichaGoogleMiNegocioRouteImport.update({
    id: '/ficha-google-mi-negocio',
    path: '/ficha-google-mi-negocio',
    getParentRoute: () => MainRoute,
  } as any)
const MainPosicionamientoLocalRoute =
  MainPosicionamientoLocalRouteImport.update({
    id: '/posicionamiento-local',
    path: '/posicionamiento-local',
    getParentRoute: () => MainRoute,
  } as any)
const MainSeoLocalBarcelonaRoute = MainSeoLocalBarcelonaRouteImport.update({
  id: '/seo-local-barcelona',
  path: '/seo-local-barcelona',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalBilbaoRoute = MainSeoLocalBilbaoRouteImport.update({
  id: '/seo-local-bilbao',
  path: '/seo-local-bilbao',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalCordobaRoute = MainSeoLocalCordobaRouteImport.update({
  id: '/seo-local-cordoba',
  path: '/seo-local-cordoba',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalMadridRoute = MainSeoLocalMadridRouteImport.update({
  id: '/seo-local-madrid',
  path: '/seo-local-madrid',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalMalagaRoute = MainSeoLocalMalagaRouteImport.update({
  id: '/seo-local-malaga',
  path: '/seo-local-malaga',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalMurciaRoute = MainSeoLocalMurciaRouteImport.update({
  id: '/seo-local-murcia',
  path: '/seo-local-murcia',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalSevillaRoute = MainSeoLocalSevillaRouteImport.update({
  id: '/seo-local-sevilla',
  path: '/seo-local-sevilla',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalValenciaRoute = MainSeoLocalValenciaRouteImport.update({
  id: '/seo-local-valencia',
  path: '/seo-local-valencia',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoLocalZaragozaRoute = MainSeoLocalZaragozaRouteImport.update({
  id: '/seo-local-zaragoza',
  path: '/seo-local-zaragoza',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaAbogadosRoute = MainSeoParaAbogadosRouteImport.update({
  id: '/seo-para-abogados',
  path: '/seo-para-abogados',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaAutonomosRoute = MainSeoParaAutonomosRouteImport.update({
  id: '/seo-para-autonomos',
  path: '/seo-para-autonomos',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaClinicasRoute = MainSeoParaClinicasRouteImport.update({
  id: '/seo-para-clinicas',
  path: '/seo-para-clinicas',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaDentistasRoute = MainSeoParaDentistasRouteImport.update({
  id: '/seo-para-dentistas',
  path: '/seo-para-dentistas',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaEntrenadoresRoute = MainSeoParaEntrenadoresRouteImport.update({
  id: '/seo-para-entrenadores',
  path: '/seo-para-entrenadores',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaFisioterapeutasRoute =
  MainSeoParaFisioterapeutasRouteImport.update({
    id: '/seo-para-fisioterapeutas',
    path: '/seo-para-fisioterapeutas',
    getParentRoute: () => MainRoute,
  } as any)
const MainSeoParaFontanerosRoute = MainSeoParaFontanerosRouteImport.update({
  id: '/seo-para-fontaneros',
  path: '/seo-para-fontaneros',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaGimnasiosRoute = MainSeoParaGimnasiosRouteImport.update({
  id: '/seo-para-gimnasios',
  path: '/seo-para-gimnasios',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaInmobiliariasRoute =
  MainSeoParaInmobiliariasRouteImport.update({
    id: '/seo-para-inmobiliarias',
    path: '/seo-para-inmobiliarias',
    getParentRoute: () => MainRoute,
  } as any)
const MainSeoParaNegociosLocalesRoute =
  MainSeoParaNegociosLocalesRouteImport.update({
    id: '/seo-para-negocios-locales',
    path: '/seo-para-negocios-locales',
    getParentRoute: () => MainRoute,
  } as any)
const MainSeoParaPintoresRoute = MainSeoParaPintoresRouteImport.update({
  id: '/seo-para-pintores',
  path: '/seo-para-pintores',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaPsicologosRoute = MainSeoParaPsicologosRouteImport.update({
  id: '/seo-para-psicologos',
  path: '/seo-para-psicologos',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaReformasRoute = MainSeoParaReformasRouteImport.update({
  id: '/seo-para-reformas',
  path: '/seo-para-reformas',
  getParentRoute: () => MainRoute,
} as any)
const MainSeoParaYogaRoute = MainSeoParaYogaRouteImport.update({
  id: '/seo-para-yoga',
  path: '/seo-para-yoga',
  getParentRoute: () => MainRoute,
} as any)
const MainServiciosRoute = MainServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogSlugRoute = MainBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute =
  MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRouteImport.update({
    id: '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio',
    path: '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio',
    getParentRoute: () => MainRoute,
  } as any)
const ApiPublicSubmitIndexnowRoute = ApiPublicSubmitIndexnowRouteImport.update({
  id: '/api/public/submit-indexnow',
  path: '/api/public/submit-indexnow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/sistema': typeof SistemaRoute
  '/$': typeof MainSplatRoute
  '/aparecer-en-google-maps': typeof MainAparecerEnGoogleMapsRoute
  '/como-funciona': typeof MainComoFuncionaRoute
  '/como-salir-primero-en-google': typeof MainComoSalirPrimeroEnGoogleRoute
  '/como-ve-google-mi-web': typeof MainComoVeGoogleMiWebRoute
  '/contacto': typeof MainContactoRoute
  '/ficha-google-mi-negocio': typeof MainFichaGoogleMiNegocioRoute
  '/posicionamiento-local': typeof MainPosicionamientoLocalRoute
  '/seo-local-barcelona': typeof MainSeoLocalBarcelonaRoute
  '/seo-local-bilbao': typeof MainSeoLocalBilbaoRoute
  '/seo-local-cordoba': typeof MainSeoLocalCordobaRoute
  '/seo-local-madrid': typeof MainSeoLocalMadridRoute
  '/seo-local-malaga': typeof MainSeoLocalMalagaRoute
  '/seo-local-murcia': typeof MainSeoLocalMurciaRoute
  '/seo-local-sevilla': typeof MainSeoLocalSevillaRoute
  '/seo-local-valencia': typeof MainSeoLocalValenciaRoute
  '/seo-local-zaragoza': typeof MainSeoLocalZaragozaRoute
  '/seo-para-abogados': typeof MainSeoParaAbogadosRoute
  '/seo-para-autonomos': typeof MainSeoParaAutonomosRoute
  '/seo-para-clinicas': typeof MainSeoParaClinicasRoute
  '/seo-para-dentistas': typeof MainSeoParaDentistasRoute
  '/seo-para-entrenadores': typeof MainSeoParaEntrenadoresRoute
  '/seo-para-fisioterapeutas': typeof MainSeoParaFisioterapeutasRoute
  '/seo-para-fontaneros': typeof MainSeoParaFontanerosRoute
  '/seo-para-gimnasios': typeof MainSeoParaGimnasiosRoute
  '/seo-para-inmobiliarias': typeof MainSeoParaInmobiliariasRoute
  '/seo-para-negocios-locales': typeof MainSeoParaNegociosLocalesRoute
  '/seo-para-pintores': typeof MainSeoParaPintoresRoute
  '/seo-para-psicologos': typeof MainSeoParaPsicologosRoute
  '/seo-para-reformas': typeof MainSeoParaReformasRoute
  '/seo-para-yoga': typeof MainSeoParaYogaRoute
  '/servicios': typeof MainServiciosRoute
  '/blog/$slug': typeof MainBlogSlugRoute
  '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio': typeof MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute
  '/api/public/submit-indexnow': typeof ApiPublicSubmitIndexnowRoute
  '/blog/': typeof MainBlogIndexRoute
}
export interface FileRoutesByTo {
  '/sistema': typeof SistemaRoute
  '/$': typeof MainSplatRoute
  '/aparecer-en-google-maps': typeof MainAparecerEnGoogleMapsRoute
  '/como-funciona': typeof MainComoFuncionaRoute
  '/como-salir-primero-en-google': typeof MainComoSalirPrimeroEnGoogleRoute
  '/como-ve-google-mi-web': typeof MainComoVeGoogleMiWebRoute
  '/contacto': typeof MainContactoRoute
  '/ficha-google-mi-negocio': typeof MainFichaGoogleMiNegocioRoute
  '/posicionamiento-local': typeof MainPosicionamientoLocalRoute
  '/seo-local-barcelona': typeof MainSeoLocalBarcelonaRoute
  '/seo-local-bilbao': typeof MainSeoLocalBilbaoRoute
  '/seo-local-cordoba': typeof MainSeoLocalCordobaRoute
  '/seo-local-madrid': typeof MainSeoLocalMadridRoute
  '/seo-local-malaga': typeof MainSeoLocalMalagaRoute
  '/seo-local-murcia': typeof MainSeoLocalMurciaRoute
  '/seo-local-sevilla': typeof MainSeoLocalSevillaRoute
  '/seo-local-valencia': typeof MainSeoLocalValenciaRoute
  '/seo-local-zaragoza': typeof MainSeoLocalZaragozaRoute
  '/seo-para-abogados': typeof MainSeoParaAbogadosRoute
  '/seo-para-autonomos': typeof MainSeoParaAutonomosRoute
  '/seo-para-clinicas': typeof MainSeoParaClinicasRoute
  '/seo-para-dentistas': typeof MainSeoParaDentistasRoute
  '/seo-para-entrenadores': typeof MainSeoParaEntrenadoresRoute
  '/seo-para-fisioterapeutas': typeof MainSeoParaFisioterapeutasRoute
  '/seo-para-fontaneros': typeof MainSeoParaFontanerosRoute
  '/seo-para-gimnasios': typeof MainSeoParaGimnasiosRoute
  '/seo-para-inmobiliarias': typeof MainSeoParaInmobiliariasRoute
  '/seo-para-negocios-locales': typeof MainSeoParaNegociosLocalesRoute
  '/seo-para-pintores': typeof MainSeoParaPintoresRoute
  '/seo-para-psicologos': typeof MainSeoParaPsicologosRoute
  '/seo-para-reformas': typeof MainSeoParaReformasRoute
  '/seo-para-yoga': typeof MainSeoParaYogaRoute
  '/servicios': typeof MainServiciosRoute
  '/': typeof MainIndexRoute
  '/blog/$slug': typeof MainBlogSlugRoute
  '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio': typeof MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute
  '/api/public/submit-indexnow': typeof ApiPublicSubmitIndexnowRoute
  '/blog': typeof MainBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/sistema': typeof SistemaRoute
  '/_main/$': typeof MainSplatRoute
  '/_main/aparecer-en-google-maps': typeof MainAparecerEnGoogleMapsRoute
  '/_main/como-funciona': typeof MainComoFuncionaRoute
  '/_main/como-salir-primero-en-google': typeof MainComoSalirPrimeroEnGoogleRoute
  '/_main/como-ve-google-mi-web': typeof MainComoVeGoogleMiWebRoute
  '/_main/contacto': typeof MainContactoRoute
  '/_main/ficha-google-mi-negocio': typeof MainFichaGoogleMiNegocioRoute
  '/_main/posicionamiento-local': typeof MainPosicionamientoLocalRoute
  '/_main/seo-local-barcelona': typeof MainSeoLocalBarcelonaRoute
  '/_main/seo-local-bilbao': typeof MainSeoLocalBilbaoRoute
  '/_main/seo-local-cordoba': typeof MainSeoLocalCordobaRoute
  '/_main/seo-local-madrid': typeof MainSeoLocalMadridRoute
  '/_main/seo-local-malaga': typeof MainSeoLocalMalagaRoute
  '/_main/seo-local-murcia': typeof MainSeoLocalMurciaRoute
  '/_main/seo-local-sevilla': typeof MainSeoLocalSevillaRoute
  '/_main/seo-local-valencia': typeof MainSeoLocalValenciaRoute
  '/_main/seo-local-zaragoza': typeof MainSeoLocalZaragozaRoute
  '/_main/seo-para-abogados': typeof MainSeoParaAbogadosRoute
  '/_main/seo-para-autonomos': typeof MainSeoParaAutonomosRoute
  '/_main/seo-para-clinicas': typeof MainSeoParaClinicasRoute
  '/_main/seo-para-dentistas': typeof MainSeoParaDentistasRoute
  '/_main/seo-para-entrenadores': typeof MainSeoParaEntrenadoresRoute
  '/_main/seo-para-fisioterapeutas': typeof MainSeoParaFisioterapeutasRoute
  '/_main/seo-para-fontaneros': typeof MainSeoParaFontanerosRoute
  '/_main/seo-para-gimnasios': typeof MainSeoParaGimnasiosRoute
  '/_main/seo-para-inmobiliarias': typeof MainSeoParaInmobiliariasRoute
  '/_main/seo-para-negocios-locales': typeof MainSeoParaNegociosLocalesRoute
  '/_main/seo-para-pintores': typeof MainSeoParaPintoresRoute
  '/_main/seo-para-psicologos': typeof MainSeoParaPsicologosRoute
  '/_main/seo-para-reformas': typeof MainSeoParaReformasRoute
  '/_main/seo-para-yoga': typeof MainSeoParaYogaRoute
  '/_main/servicios': typeof MainServiciosRoute
  '/_main/': typeof MainIndexRoute
  '/_main/blog/$slug': typeof MainBlogSlugRoute
  '/_main/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio': typeof MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute
  '/api/public/submit-indexnow': typeof ApiPublicSubmitIndexnowRoute
  '/_main/blog/': typeof MainBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sistema'
    | '/$'
    | '/aparecer-en-google-maps'
    | '/como-funciona'
    | '/como-salir-primero-en-google'
    | '/como-ve-google-mi-web'
    | '/contacto'
    | '/ficha-google-mi-negocio'
    | '/posicionamiento-local'
    | '/seo-local-barcelona'
    | '/seo-local-bilbao'
    | '/seo-local-cordoba'
    | '/seo-local-madrid'
    | '/seo-local-malaga'
    | '/seo-local-murcia'
    | '/seo-local-sevilla'
    | '/seo-local-valencia'
    | '/seo-local-zaragoza'
    | '/seo-para-abogados'
    | '/seo-para-autonomos'
    | '/seo-para-clinicas'
    | '/seo-para-dentistas'
    | '/seo-para-entrenadores'
    | '/seo-para-fisioterapeutas'
    | '/seo-para-fontaneros'
    | '/seo-para-gimnasios'
    | '/seo-para-inmobiliarias'
    | '/seo-para-negocios-locales'
    | '/seo-para-pintores'
    | '/seo-para-psicologos'
    | '/seo-para-reformas'
    | '/seo-para-yoga'
    | '/servicios'
    | '/blog/$slug'
    | '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
    | '/api/public/submit-indexnow'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sistema'
    | '/$'
    | '/aparecer-en-google-maps'
    | '/como-funciona'
    | '/como-salir-primero-en-google'
    | '/como-ve-google-mi-web'
    | '/contacto'
    | '/ficha-google-mi-negocio'
    | '/posicionamiento-local'
    | '/seo-local-barcelona'
    | '/seo-local-bilbao'
    | '/seo-local-cordoba'
    | '/seo-local-madrid'
    | '/seo-local-malaga'
    | '/seo-local-murcia'
    | '/seo-local-sevilla'
    | '/seo-local-valencia'
    | '/seo-local-zaragoza'
    | '/seo-para-abogados'
    | '/seo-para-autonomos'
    | '/seo-para-clinicas'
    | '/seo-para-dentistas'
    | '/seo-para-entrenadores'
    | '/seo-para-fisioterapeutas'
    | '/seo-para-fontaneros'
    | '/seo-para-gimnasios'
    | '/seo-para-inmobiliarias'
    | '/seo-para-negocios-locales'
    | '/seo-para-pintores'
    | '/seo-para-psicologos'
    | '/seo-para-reformas'
    | '/seo-para-yoga'
    | '/servicios'
    | '/'
    | '/blog/$slug'
    | '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
    | '/api/public/submit-indexnow'
    | '/blog'
  id:
    | '__root__'
    | '/_main'
    | '/sistema'
    | '/_main/$'
    | '/_main/aparecer-en-google-maps'
    | '/_main/como-funciona'
    | '/_main/como-salir-primero-en-google'
    | '/_main/como-ve-google-mi-web'
    | '/_main/contacto'
    | '/_main/ficha-google-mi-negocio'
    | '/_main/posicionamiento-local'
    | '/_main/seo-local-barcelona'
    | '/_main/seo-local-bilbao'
    | '/_main/seo-local-cordoba'
    | '/_main/seo-local-madrid'
    | '/_main/seo-local-malaga'
    | '/_main/seo-local-murcia'
    | '/_main/seo-local-sevilla'
    | '/_main/seo-local-valencia'
    | '/_main/seo-local-zaragoza'
    | '/_main/seo-para-abogados'
    | '/_main/seo-para-autonomos'
    | '/_main/seo-para-clinicas'
    | '/_main/seo-para-dentistas'
    | '/_main/seo-para-entrenadores'
    | '/_main/seo-para-fisioterapeutas'
    | '/_main/seo-para-fontaneros'
    | '/_main/seo-para-gimnasios'
    | '/_main/seo-para-inmobiliarias'
    | '/_main/seo-para-negocios-locales'
    | '/_main/seo-para-pintores'
    | '/_main/seo-para-psicologos'
    | '/_main/seo-para-reformas'
    | '/_main/seo-para-yoga'
    | '/_main/servicios'
    | '/_main/'
    | '/_main/blog/$slug'
    | '/_main/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
    | '/api/public/submit-indexnow'
    | '/_main/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SistemaRoute: typeof SistemaRoute
  ApiPublicSubmitIndexnowRoute: typeof ApiPublicSubmitIndexnowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$': {
      id: '/_main/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof MainSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/aparecer-en-google-maps': {
      id: '/_main/aparecer-en-google-maps'
      path: '/aparecer-en-google-maps'
      fullPath: '/aparecer-en-google-maps'
      preLoaderRoute: typeof MainAparecerEnGoogleMapsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/como-funciona': {
      id: '/_main/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof MainComoFuncionaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/como-salir-primero-en-google': {
      id: '/_main/como-salir-primero-en-google'
      path: '/como-salir-primero-en-google'
      fullPath: '/como-salir-primero-en-google'
      preLoaderRoute: typeof MainComoSalirPrimeroEnGoogleRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/como-ve-google-mi-web': {
      id: '/_main/como-ve-google-mi-web'
      path: '/como-ve-google-mi-web'
      fullPath: '/como-ve-google-mi-web'
      preLoaderRoute: typeof MainComoVeGoogleMiWebRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contacto': {
      id: '/_main/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof MainContactoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ficha-google-mi-negocio': {
      id: '/_main/ficha-google-mi-negocio'
      path: '/ficha-google-mi-negocio'
      fullPath: '/ficha-google-mi-negocio'
      preLoaderRoute: typeof MainFichaGoogleMiNegocioRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/posicionamiento-local': {
      id: '/_main/posicionamiento-local'
      path: '/posicionamiento-local'
      fullPath: '/posicionamiento-local'
      preLoaderRoute: typeof MainPosicionamientoLocalRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-barcelona': {
      id: '/_main/seo-local-barcelona'
      path: '/seo-local-barcelona'
      fullPath: '/seo-local-barcelona'
      preLoaderRoute: typeof MainSeoLocalBarcelonaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-bilbao': {
      id: '/_main/seo-local-bilbao'
      path: '/seo-local-bilbao'
      fullPath: '/seo-local-bilbao'
      preLoaderRoute: typeof MainSeoLocalBilbaoRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-cordoba': {
      id: '/_main/seo-local-cordoba'
      path: '/seo-local-cordoba'
      fullPath: '/seo-local-cordoba'
      preLoaderRoute: typeof MainSeoLocalCordobaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-madrid': {
      id: '/_main/seo-local-madrid'
      path: '/seo-local-madrid'
      fullPath: '/seo-local-madrid'
      preLoaderRoute: typeof MainSeoLocalMadridRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-malaga': {
      id: '/_main/seo-local-malaga'
      path: '/seo-local-malaga'
      fullPath: '/seo-local-malaga'
      preLoaderRoute: typeof MainSeoLocalMalagaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-murcia': {
      id: '/_main/seo-local-murcia'
      path: '/seo-local-murcia'
      fullPath: '/seo-local-murcia'
      preLoaderRoute: typeof MainSeoLocalMurciaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-sevilla': {
      id: '/_main/seo-local-sevilla'
      path: '/seo-local-sevilla'
      fullPath: '/seo-local-sevilla'
      preLoaderRoute: typeof MainSeoLocalSevillaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-valencia': {
      id: '/_main/seo-local-valencia'
      path: '/seo-local-valencia'
      fullPath: '/seo-local-valencia'
      preLoaderRoute: typeof MainSeoLocalValenciaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-local-zaragoza': {
      id: '/_main/seo-local-zaragoza'
      path: '/seo-local-zaragoza'
      fullPath: '/seo-local-zaragoza'
      preLoaderRoute: typeof MainSeoLocalZaragozaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-abogados': {
      id: '/_main/seo-para-abogados'
      path: '/seo-para-abogados'
      fullPath: '/seo-para-abogados'
      preLoaderRoute: typeof MainSeoParaAbogadosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-autonomos': {
      id: '/_main/seo-para-autonomos'
      path: '/seo-para-autonomos'
      fullPath: '/seo-para-autonomos'
      preLoaderRoute: typeof MainSeoParaAutonomosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-clinicas': {
      id: '/_main/seo-para-clinicas'
      path: '/seo-para-clinicas'
      fullPath: '/seo-para-clinicas'
      preLoaderRoute: typeof MainSeoParaClinicasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-dentistas': {
      id: '/_main/seo-para-dentistas'
      path: '/seo-para-dentistas'
      fullPath: '/seo-para-dentistas'
      preLoaderRoute: typeof MainSeoParaDentistasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-entrenadores': {
      id: '/_main/seo-para-entrenadores'
      path: '/seo-para-entrenadores'
      fullPath: '/seo-para-entrenadores'
      preLoaderRoute: typeof MainSeoParaEntrenadoresRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-fisioterapeutas': {
      id: '/_main/seo-para-fisioterapeutas'
      path: '/seo-para-fisioterapeutas'
      fullPath: '/seo-para-fisioterapeutas'
      preLoaderRoute: typeof MainSeoParaFisioterapeutasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-fontaneros': {
      id: '/_main/seo-para-fontaneros'
      path: '/seo-para-fontaneros'
      fullPath: '/seo-para-fontaneros'
      preLoaderRoute: typeof MainSeoParaFontanerosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-gimnasios': {
      id: '/_main/seo-para-gimnasios'
      path: '/seo-para-gimnasios'
      fullPath: '/seo-para-gimnasios'
      preLoaderRoute: typeof MainSeoParaGimnasiosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-inmobiliarias': {
      id: '/_main/seo-para-inmobiliarias'
      path: '/seo-para-inmobiliarias'
      fullPath: '/seo-para-inmobiliarias'
      preLoaderRoute: typeof MainSeoParaInmobiliariasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-negocios-locales': {
      id: '/_main/seo-para-negocios-locales'
      path: '/seo-para-negocios-locales'
      fullPath: '/seo-para-negocios-locales'
      preLoaderRoute: typeof MainSeoParaNegociosLocalesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-pintores': {
      id: '/_main/seo-para-pintores'
      path: '/seo-para-pintores'
      fullPath: '/seo-para-pintores'
      preLoaderRoute: typeof MainSeoParaPintoresRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-psicologos': {
      id: '/_main/seo-para-psicologos'
      path: '/seo-para-psicologos'
      fullPath: '/seo-para-psicologos'
      preLoaderRoute: typeof MainSeoParaPsicologosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-reformas': {
      id: '/_main/seo-para-reformas'
      path: '/seo-para-reformas'
      fullPath: '/seo-para-reformas'
      preLoaderRoute: typeof MainSeoParaReformasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/seo-para-yoga': {
      id: '/_main/seo-para-yoga'
      path: '/seo-para-yoga'
      fullPath: '/seo-para-yoga'
      preLoaderRoute: typeof MainSeoParaYogaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/servicios': {
      id: '/_main/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof MainServiciosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$slug': {
      id: '/_main/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MainBlogSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio': {
      id: '/_main/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
      path: '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
      fullPath: '/blog/seo-local-mejor-estrategia-marketing-nuevo-negocio'
      preLoaderRoute: typeof MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/public/submit-indexnow': {
      id: '/api/public/submit-indexnow'
      path: '/api/public/submit-indexnow'
      fullPath: '/api/public/submit-indexnow'
      preLoaderRoute: typeof ApiPublicSubmitIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainSplatRoute: typeof MainSplatRoute
  MainAparecerEnGoogleMapsRoute: typeof MainAparecerEnGoogleMapsRoute
  MainComoFuncionaRoute: typeof MainComoFuncionaRoute
  MainComoSalirPrimeroEnGoogleRoute: typeof MainComoSalirPrimeroEnGoogleRoute
  MainComoVeGoogleMiWebRoute: typeof MainComoVeGoogleMiWebRoute
  MainContactoRoute: typeof MainContactoRoute
  MainFichaGoogleMiNegocioRoute: typeof MainFichaGoogleMiNegocioRoute
  MainPosicionamientoLocalRoute: typeof MainPosicionamientoLocalRoute
  MainSeoLocalBarcelonaRoute: typeof MainSeoLocalBarcelonaRoute
  MainSeoLocalBilbaoRoute: typeof MainSeoLocalBilbaoRoute
  MainSeoLocalCordobaRoute: typeof MainSeoLocalCordobaRoute
  MainSeoLocalMadridRoute: typeof MainSeoLocalMadridRoute
  MainSeoLocalMalagaRoute: typeof MainSeoLocalMalagaRoute
  MainSeoLocalMurciaRoute: typeof MainSeoLocalMurciaRoute
  MainSeoLocalSevillaRoute: typeof MainSeoLocalSevillaRoute
  MainSeoLocalValenciaRoute: typeof MainSeoLocalValenciaRoute
  MainSeoLocalZaragozaRoute: typeof MainSeoLocalZaragozaRoute
  MainSeoParaAbogadosRoute: typeof MainSeoParaAbogadosRoute
  MainSeoParaAutonomosRoute: typeof MainSeoParaAutonomosRoute
  MainSeoParaClinicasRoute: typeof MainSeoParaClinicasRoute
  MainSeoParaDentistasRoute: typeof MainSeoParaDentistasRoute
  MainSeoParaEntrenadoresRoute: typeof MainSeoParaEntrenadoresRoute
  MainSeoParaFisioterapeutasRoute: typeof MainSeoParaFisioterapeutasRoute
  MainSeoParaFontanerosRoute: typeof MainSeoParaFontanerosRoute
  MainSeoParaGimnasiosRoute: typeof MainSeoParaGimnasiosRoute
  MainSeoParaInmobiliariasRoute: typeof MainSeoParaInmobiliariasRoute
  MainSeoParaNegociosLocalesRoute: typeof MainSeoParaNegociosLocalesRoute
  MainSeoParaPintoresRoute: typeof MainSeoParaPintoresRoute
  MainSeoParaPsicologosRoute: typeof MainSeoParaPsicologosRoute
  MainSeoParaReformasRoute: typeof MainSeoParaReformasRoute
  MainSeoParaYogaRoute: typeof MainSeoParaYogaRoute
  MainServiciosRoute: typeof MainServiciosRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogSlugRoute: typeof MainBlogSlugRoute
  MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute: typeof MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSplatRoute: MainSplatRoute,
  MainAparecerEnGoogleMapsRoute: MainAparecerEnGoogleMapsRoute,
  MainComoFuncionaRoute: MainComoFuncionaRoute,
  MainComoSalirPrimeroEnGoogleRoute: MainComoSalirPrimeroEnGoogleRoute,
  MainComoVeGoogleMiWebRoute: MainComoVeGoogleMiWebRoute,
  MainContactoRoute: MainContactoRoute,
  MainFichaGoogleMiNegocioRoute: MainFichaGoogleMiNegocioRoute,
  MainPosicionamientoLocalRoute: MainPosicionamientoLocalRoute,
  MainSeoLocalBarcelonaRoute: MainSeoLocalBarcelonaRoute,
  MainSeoLocalBilbaoRoute: MainSeoLocalBilbaoRoute,
  MainSeoLocalCordobaRoute: MainSeoLocalCordobaRoute,
  MainSeoLocalMadridRoute: MainSeoLocalMadridRoute,
  MainSeoLocalMalagaRoute: MainSeoLocalMalagaRoute,
  MainSeoLocalMurciaRoute: MainSeoLocalMurciaRoute,
  MainSeoLocalSevillaRoute: MainSeoLocalSevillaRoute,
  MainSeoLocalValenciaRoute: MainSeoLocalValenciaRoute,
  MainSeoLocalZaragozaRoute: MainSeoLocalZaragozaRoute,
  MainSeoParaAbogadosRoute: MainSeoParaAbogadosRoute,
  MainSeoParaAutonomosRoute: MainSeoParaAutonomosRoute,
  MainSeoParaClinicasRoute: MainSeoParaClinicasRoute,
  MainSeoParaDentistasRoute: MainSeoParaDentistasRoute,
  MainSeoParaEntrenadoresRoute: MainSeoParaEntrenadoresRoute,
  MainSeoParaFisioterapeutasRoute: MainSeoParaFisioterapeutasRoute,
  MainSeoParaFontanerosRoute: MainSeoParaFontanerosRoute,
  MainSeoParaGimnasiosRoute: MainSeoParaGimnasiosRoute,
  MainSeoParaInmobiliariasRoute: MainSeoParaInmobiliariasRoute,
  MainSeoParaNegociosLocalesRoute: MainSeoParaNegociosLocalesRoute,
  MainSeoParaPintoresRoute: MainSeoParaPintoresRoute,
  MainSeoParaPsicologosRoute: MainSeoParaPsicologosRoute,
  MainSeoParaReformasRoute: MainSeoParaReformasRoute,
  MainSeoParaYogaRoute: MainSeoParaYogaRoute,
  MainServiciosRoute: MainServiciosRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogSlugRoute: MainBlogSlugRoute,
  MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute:
    MainBlogSeoLocalMejorEstrategiaMarketingNuevoNegocioRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SistemaRoute: SistemaRoute,
  ApiPublicSubmitIndexnowRoute: ApiPublicSubmitIndexnowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
